env:
  global:
    - CC_TEST_REPORTER_ID=8682688bc269d0f558949836dc3a7da18cd504940d6a4034c4539203dbe3fa22

language: go
go:
  - 1.9.x

# Setup caching of dependencies
# before_cache:
# - rm -rf $GOPATH/src/github.com/ipfs-search/*
# - rm -rf $GOPATH/pkg/**/github.com/ipfs-search/ipfs-search
# cache:
#   directories:
#     - $GOPATH/src
#     - $GOPATH/pkg

install: go get -t -v ./...

before_script:
  # Install CodeClimate test reporter
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script: |
  # Thank https://stackoverflow.com/questions/45776043/codeclimate-test-coverage-formatter-for-golang
  for pkg in $(go list ./... | grep -v vendor); do
      go test -coverprofile=$(echo $pkg | tr / -).cover $pkg
  done
  echo "mode: set" > c.out
  grep -h -v "^mode:" ./*.cover >> c.out
  rm -f *.cover

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

# Matrix/Riot webhook notifications
notifications:
  email: false
  webhooks:
    urls:
        - "https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0MGRva3RlcmJvYiUzQWNoYXQud2Voby5zdC8lMjFNR1pUZWlZUm9XZllmSmxMckUlM0FjaGF0LndlaG8uc3Q"
    on_success: change  # always|never|change
    on_failure: always
    on_start: never
