ipfs:
  api_url: localhost:5001
  timeout: 6m0s
elasticsearch:
  url: http://localhost:9200
amqp:
  url: amqp://guest:guest@localhost:5672/
crawler:
  retry_wait: 2s
  hash_wait: 100ms
  file_wait: 100ms
  partial_size: 256KB
  hash_workers: 140
  file_workers: 120
  metadata_max_size: 50MB
sniffer:
  lastseen_expiration: 1h0m0s
  lastseen_prunelen: 32768
  logger_timeout: 1m0s
  buffer_size: 512
indexes:
  directories:
    name: ipfs_directories
  files:
    name: ipfs_files
  invalids:
    name: ipfs_invalids
extractor:
  url: http://localhost:8081
  timeout: 5m0s
  retry_wait: 2s
